"""Assemble panels into a LaTeX document and compile it.

Two files are written for every figure:

``<name>.tex``       standalone document; compile it on its own (pdflatex).
``<name>-body.tex``  colour definitions + the tikzpicture only, for
                     ``\\input{...}`` inside a thesis.  The thesis preamble
                     needs ``\\usepackage{tikz}`` and
                     ``\\usetikzlibrary{arrows.meta,positioning}``.
"""

import shutil
import subprocess
from pathlib import Path

from . import glyphs
from .panels import PANELS, trajectory
from .tikz import num, pt

TIKZ_LIBRARIES = "arrows.meta,positioning"


def color_definitions(cfg):
    lines = []
    for name, hexcode in cfg.style.colors.items():
        hexcode = str(hexcode).lstrip("#").upper()
        if len(hexcode) != 6:
            raise ValueError(f"style.colors.{name}: '{hexcode}' is not a 6-digit hex colour")
        lines.append(f"\\definecolor{{df{name}}}{{HTML}}{{{hexcode}}}")
    return "\n".join(lines)


def picture(cfg):
    """Return the tikzpicture source for the whole figure."""
    glyphs.PALETTE.clear()
    glyphs.PALETTE.update(cfg.style.colors)
    unknown = [p for p in cfg.layout.panels if p not in PANELS]
    if unknown:
        raise ValueError(f"layout.panels: unknown panel(s) {unknown}; choose from {list(PANELS)}")
    out = [f"\\begin{{tikzpicture}}[line width={num(cfg.style.line_width)}pt, scale={num(cfg.document.scale)}, "
           f"line cap=round, line join=round]"]
    for i, name in enumerate(cfg.layout.panels):
        canvas = PANELS[name](cfg)
        off = cfg.layout[name]
        out.append(f"% ===================== panel: {name}")
        out.append(f"\\begin{{scope}}[shift={{{pt(off.x, off.y)}}}]")
        out.append(canvas.tikz())
        if cfg.layout.panel_letters and len(cfg.layout.panels) > 1:
            x, y = off.letter if off.get("letter") else canvas.anchors["_letter"]
            out.append(f"\\node[anchor=north west, inner sep=0pt, font={{\\sffamily{cfg.layout.letter_style}}}, "
                       f"text=dftext] at {pt(x, y)} {{({chr(ord('a') + i)})}};")
        out.append("\\end{scope}")
    out.append("\\end{tikzpicture}")
    return "\n".join(out)


def body(cfg):
    return (f"% {cfg.instrument.name}: generated by detfig from YAML; edit the YAML, not this file\n"
            f"% needs: \\usepackage{{tikz}} \\usetikzlibrary{{{TIKZ_LIBRARIES}}}"
            + "".join(f" \\usepackage{{{p}}}" for p in trajectory.latex_packages(cfg)) + "\n"
            f"{color_definitions(cfg)}\n{picture(cfg)}\n")


def standalone(cfg):
    extra = "".join(f"\\usepackage{{{p}}}\n" for p in trajectory.latex_packages(cfg))
    return (f"\\documentclass[border={cfg.document.border}]{{standalone}}\n"
            f"\\usepackage[T1]{{fontenc}}\n\\usepackage{{lmodern}}\n\\usepackage{{tikz}}\n{extra}"
            f"\\usetikzlibrary{{{TIKZ_LIBRARIES}}}\n{cfg.document.preamble}\n"
            f"\\begin{{document}}\n{body(cfg)}\\end{{document}}\n")


def write(cfg, outdir, compile_pdf=True):
    """Write the .tex files (and PDF/PNG if pdflatex is available). Returns paths."""
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    name = cfg.output.name
    tex = outdir / f"{name}.tex"
    tex.write_text(standalone(cfg))
    (outdir / f"{name}-body.tex").write_text(body(cfg))
    written = {"tex": tex}
    if not compile_pdf:
        return written
    if not shutil.which("pdflatex"):
        print("pdflatex not found: wrote .tex only")
        return written
    run = subprocess.run(["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex.name],
                         cwd=outdir, capture_output=True, text=True)
    if run.returncode != 0:
        lines = run.stdout.splitlines()
        errors = [" | ".join(lines[i:i + 3]) for i, ln in enumerate(lines) if ln.startswith("!")]
        detail = "\n".join(errors) if errors else "\n".join(lines[-25:])
        raise RuntimeError(f"pdflatex failed on {tex} (full log: {tex.with_suffix('.log')}):\n{detail}")
    for ext in ("aux", "log"):
        (outdir / f"{name}.{ext}").unlink(missing_ok=True)
    written["pdf"] = outdir / f"{name}.pdf"
    if cfg.output.png_dpi and shutil.which("pdftoppm"):
        subprocess.run(["pdftoppm", "-png", "-singlefile", "-r", str(cfg.output.png_dpi),
                        written["pdf"].name, name], cwd=outdir, check=True)
        written["png"] = outdir / f"{name}.png"
    return written
